apiVersion: mke.mirantis.com/v1alpha1
kind: MkeConfig
metadata:
  name: mke
  namespace: mke
spec:
  hosts:
  - role: controller+worker
    ssh:
      address: 192.168.65.2
      port: 22
      user: rsingh
      keyPath: /Users/rsingh/.colima/_lima/_config/user
      installFlags:
      - --profile=none
  addons: []
  apiServer:
    externalAddress: 192.168.65.2:33001
    audit:
      enabled: false
      logPath: /var/lib/k0s/audit.log
      maxAge: 30
      maxBackup: 10
      maxSize: 10
    encryptionProvider: /var/lib/k0s/encryption.cfg
    eventRateLimit:
      enabled: false
    port: 6443
    profilingEnabled: true
    requestTimeout: 1m
    sans:
    - 192.168.65.2
  authentication:
    expiry:
      refreshTokens: {}
    ldap:
      enabled: false
    oidc:
      enabled: false
    saml:
      enabled: false
  backup:
    enabled: true
    scheduled_backup:
      enabled: false
    storage_provider:
      external_options: {}
      in_cluster_options:
        admin_credentials_secret: minio-credentials
        enable_ui: true
      type: InCluster
  cloudProvider:
    enabled: false
  controllerManager:
    profilingEnabled: true
    terminatedPodGCThreshold: 12500
  devicePlugins:
    nvidiaGPU:
      enabled: false
  dns:
    lameduck:
      duration: 7s
  etcd: {}
  ingressController:
    affinity:
      nodeAffinity: {}
    enabled: false
    extraArgs:
      defaultSslCertificate: ""
      enableSslPassthrough: false
      httpPort: 80
      httpsPort: 443
    nodePorts: {}
    ports: {}
    replicaCount: 2
  kubelet:
    eventRecordQPS: 50
    managerKubeReserved:
      cpu: 250m
      ephemeral-storage: 4Gi
      memory: 2Gi
    maxPods: 110
    podPidsLimit: -1
    podsPerCore: 0
    protectKernelDefaults: false
    seccompDefault: true
    workerKubeReserved:
      cpu: 50m
      ephemeral-storage: 500Mi
      memory: 300Mi
    customProfiles:
      - name: none
        values: {}
  monitoring:
    enableCAdvisor: false
    enableGrafana: true
    enableOpscare: false
  network:
    cplb:
      disabled: true
    kubeProxy:
      iptables:
        minSyncPeriod: 0s
        syncPeriod: 0s
      metricsBindAddress: 0.0.0.0:10249
      mode: iptables
    nllb:
      disabled: true
    nodePortRange: 32768-35535
    providers:
    - enabled: true
      extraConfig:
        deployWithOperator: "false"
      provider: custom
    serviceCIDR: 10.96.0.0/16
  policyController:
    opaGatekeeper:
      enabled: false
  scheduler:
    profilingEnabled: true
  tracking:
    enabled: false
