apiVersion: v1
kind: Namespace
metadata:
  name:  kc-paris
---
apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: demo
  namespace: kc-paris
spec:
  version: v1.29.1-k0s.0
  service:
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/location: fsn1
