apiVersion: autopilot.k0sproject.io/v1beta2
kind: Plan
metadata:
  name: autopilot

spec:
  id: id1234
  timestamp: now

  commands:
    - k0supdate:
        version: v1.29.1+k0s.1
        platforms:
          linux-arm64:
            url: https://github.com/k0sproject/k0s/releases/download/v1.29.1+k0s.1/k0s-v1.29.1+k0s.1-arm64
        targets:
          controllers:
            discovery:
              static:
                nodes:
                  - k0sctl-controller
          workers:
            limits:
              concurrent: 1
            discovery:
              selector: {}
                